version: '2'  

services:  
  nginx:
    image: nginx:1.13
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    ports:
      - "8000:8000"
    volumes:
      - ../site:/${COMPOSE_PROJECT_NAME}
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    volumes_from:
      - php
    depends_on:
      - php

  postgres:
      image: postgres:9.6
      container_name: ${COMPOSE_PROJECT_NAME}_postgres
      volumes:
        - db:/var/lib/postgresql/data
        - ./db/:/db/
      ports: 
        - "5432:5432"
      environment:
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASS}
        - POSTGRES_DB=${DB_NAME}

volumes:
    db:
        driver: local